params:
  batch_size_gpu: 262144
  batch_size_cpu: 20
  epochs_gpu: 100
  epochs_cpu: 20
  topk: 10
  neg_test: 100
  neg_train: 4
  lr: 1e-3
  #The maximum embedding dimension
  emb_dim: 50 
  #Number of events to wait if no improvement and then stop the training.
  patience: 10 
  #The number of positive samples to create testset. 
  pos_sample: 20 
data:
    test: test_pos_neg
    all_features_sub: merged_sub_clean.csv
    all_features: merged_all_clean.csv
    title_emb: job_title_embed3
meta_file:
    apps: apps.tsv
    jobs: jobs.tsv
    user_histroy: user_history.tsv
    users: users.tsv
leave_one_data:
    train_pos: leave_one_train.csv
    train_neg: leave_one_train_neg
    test_pos_neg: test_pos_neg
    hdf5: leave_one_train.hdf5
global_temp_data:
    train_pos: train_pos
    test_pos: test_pos
    train_neg: train_neg
    test_neg: test_neg
    test_pos_sub: test_pos_sub
path:
  root: ../data/jobs
  root_tsv: ../data/jobs/tsv
  global_temp: ../data/jobs/global_temp
  leave_one: ../data/jobs/leave_one
  leave_one_cf: ../../data/jobs/leave_one
name:
  cf_name: my-cf-project 


