params:
  batch_size_gpu: 1048576
  batch_size_cpu: 20
  epochs_gpu: 100
  epochs_cpu: 20
  topk: 10
  neg_test: 100
  neg_train: 4
  lr: 1e-3
  emb_dim: 50 #The maximum embedding dimension
  patience: 10 #Number of events to wait if no improvement and then stop the training.
  
file:
    train_pos: leave_one_train.csv
    train_neg: leave_one_train_neg
    test: test_pos_neg
    all_features: merged_sub_clean.csv

path:
  root: ../../data/jobs
